version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        volumes:
            - /data_directory_path/config/sabnzbd:/config
            - /data_directory_path/Downloads/complete:/downloads
            - /data_directory_path/Downloads/incomplete:/incomplete-downloads
        ports:
            - 8080:8080
        env_file: uidgid.env
        environment:
            - EDGE=1
            - VIRTUAL_HOST=sabnzbd.HOSTNAME.com
            - VIRTUAL_PORT=8080
        restart: always

    plexrequests:
        image: linuxserver/plexrequests:latest
        container_name: plexrequests
        volumes:
            - /data_directory_path/config/plexrequests:/config
        ports:
            - 3000:3000
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plexrequests.HOSTNAME.com
            - VIRTUAL_PORT=3000
        restart: always

    couchpotato:
        image: linuxserver/couchpotato:latest
        container_name: couchpotato
        volumes:
            - /data_directory_path/config/couchpotato:/config
            - /data_directory_path/Downloads/complete:/downloads
            - /data_directory_path/Movies:/movies
        ports:
            - 5050:5050
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=couchpotato.HOSTNAME.com
            - VIRTUAL_PORT=5050
        restart: always

    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - /data_directory_path/config/plex:/config
            - /data_directory_path/TV:/data/tvshows
            - /data_directory_path/Movies:/data/movies
        ports:
            - 32469:32469
            - 32400:32400
            - 32401:32401
            - 3005:3005
            - 8324:8324
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plex.HOSTNAME.com
            - VIRTUAL_PORT=32400
        restart: always

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /data_directory_path/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /data_directory_path/TV:/tv
            - /data_directory_path/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.HOSTNAME.com
            - VIRTUAL_PORT=8989
        restart: always

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - /data_directory_path/config/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - /data_directory_path/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plexpy.HOSTNAME.com
            - VIRTUAL_PORT=8181
        restart: always

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - /data_directory_path/config/nzbhydra:/config
            - /data_directory_path/Downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbhydra.HOSTNAME.com
            - VIRTUAL_PORT=5075
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /data_directory_path/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.HOSTNAME.com
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /data_directory_path/config/radarr:/config
            - /data_directory_path/Movies:/movies
            - /data_directory_path/Downloads/complete:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.HOSTNAME.com
            - VIRTUAL_PORT=7878
        restart: always

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - /data_directory_path/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=ombi.HOSTNAME.com
            - VIRTUAL_PORT=3579
        restart: always

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /data_directory_path/config/nzbget:/config
            - /data_directory_path/Downloads/complete:/complete
            - /data_directory_path/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbget.HOSTNAME.com
            - VIRTUAL_PORT=6789
        restart: always